services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.5.0
    container_name: automotive-elasticsearch

    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m

    ports:
      - "9200:9200"

    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30


  kibana:
    image: docker.elastic.co/kibana/kibana:9.5.0
    container_name: automotive-kibana

    depends_on:
      elasticsearch:
        condition: service_healthy

    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      I18N_DEFAULTLOCALE: "en"
      I18N_LOCALES: '["en"]'
      I18N_ALLOWLOCALECOOKIE: "false"

    ports:
      - "5601:5601"


volumes:
  elasticsearch-data: